#!/bin/sh -e

. "$(dirname "$0")/common"

usage () {
    err "This tool lets you set the contents of files in the Cassandra config directory:"
    err "\`cat cassandra.yaml | sudo /snap/bin/cassandra.config-set cassandra.yaml\`"
}

err () {
    echo "$1" >&2
}

if [ -z "$SNAP_DATA" ]; then
    err "SNAP_DATA not set."
    exit 1
fi

if [ $(id -u) != 0 ]; then
    err "Please re-run as root."
    err
    usage
    exit 1
fi

if [ -t 0 ] || [ -z "$1" ]; then
    usage
    exit 1
else
    cat - > $CASSANDRA_CONF/$1
fi
