#!/bin/sh

. "$(dirname "$0")/common"

[ -e "$CASSANDRA_CONF" ] || mkdir "$CASSANDRA_CONF"
[ -e "$CASSANDRA_LOGS" ] || mkdir "$CASSANDRA_LOGS"
[ -e "$CASSANDRA_DATA" ] || mkdir "$CASSANDRA_DATA"

# Required config files. Use the default if one is not provided.
for f in cassandra.yaml logback.xml cassandra-env.sh jvm.options; do
    if [ ! -e "$CASSANDRA_CONF/$f" ]; then
        if [ "$f" = "cassandra-env.sh" ]; then
            # Libraries are in /usr/share/cassandra, not CASSANDRA_HOME
            sed 's,\$CASSANDRA_HOME/lib,$SNAP/usr/share/cassandra/lib,' \
                "$STATIC_CONF/$f" > "$CASSANDRA_CONF/$f"
        else
            cp "$STATIC_CONF/$f" "$CASSANDRA_CONF/$f"
        fi
    fi
done

export cassandra_storagedir="$CASSANDRA_DATA"
export JVM_OPTS="$JVM_OPTS -Dcassandra.config=file://$CASSANDRA_CONF/cassandra.yaml"

# The -x bit isn't set on cassandra
/bin/sh $SNAP/usr/sbin/cassandra -f -R
