#!/bin/sh

CASSANDRA_HOME="$SNAP/usr/share/cassandra"
CASSANDRA_CONF="$SNAP/etc/cassandra"

if [ ! -e "$SNAP_DATA/cassandra.yaml" ]; then
    # Use the default if a config file hasn't been provided.
    cp $CASSANDRA_CONF/cassandra.yaml $SNAP_DATA/cassandra.yaml
fi

# sstables, etc
cassandra_storagedir="$SNAP_DATA/data"

for jar in "$CASSANDRA_HOME"/lib/*.jar; do
    CLASSPATH="$CLASSPATH:$jar"
done
JAVA_AGENT="$JAVA_AGENT -javaagent:$CASSANDRA_HOME/lib/jamm-0.3.0.jar"

JVM_OPTS="$JVM_OPTS -Dcassandra.logdir=$SNAP_DATA/logs"
JVM_OPTS="$JVM_OPTS -Dcassandra.config=file://$SNAP_DATA/cassandra.yaml"

. $SNAP/usr/sbin/cassandra
